# Generated by Django 5.0.6 on 2024-08-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
